apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-d44e"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-d44e"
  template:
    metadata:
      labels:
        app: "aksdemo-d44e"
    spec:
      containers:
        - name: "aksdemo-d44e"
          image: "acrdemokubernetes.azurecr.io/aksdemo"
          ports:
          - containerPort: 80